### ISSUE TITLE
Fails to build with warnings as errors - ignoring return value of 'write'

### ISSUE THREAD

**Issue by colemickens** [vilhalmer/oguri#13]
```
[18/19] Compiling C object 'oguri@exe/oguri.c.o'.
FAILED: oguri@exe/oguri.c.o
/nix/store/ds1prvgw3i3ic8c7axyrw4lwm3d0gqab-gcc-wrapper-7.4.0/bin/cc -Ioguri@exe -I. -I.. -I/nix/store/4p0ygg1j1qd8ib734sfziw5r18w07gmv-cairo-1.16.0-dev/include/cairo -I/nix/store/c8nphb8azaxx998m41jhigl4ijb1c3sk-freetype-2.10.0-dev/include/freetype2 -I/nix/store/c8nphb8azaxx998m41jhigl4ijb1c3sk-freetype-2.10.0-dev/include -I/nix/store/mkbq9i2m8qva6s8wnw1c9yjg4zsb86p5-glib-2.60.1-dev/include -I/nix/store/mkbq9i2m8qva6s8wnw1c9yjg4zsb86p5-glib-2.60.1-dev/include/glib-2.0 -I/nix/store/yrmrvha03pvdyi9ww2bi6xjpk5930sf8-glib-2.60.1/lib/glib-2.0/include -I/nix/store/6pz21jzyq30c44rw0w2z3nw80sjhcw4i-gtk+3-3.24.8-dev/include/gtk-3.0 -I/nix/store/02cq6d4nv6c39kcn2pjy5av8agc7hl30-pango-1.43.0-dev/include/pango-1.0 -I/nix/store/wkn688d6pkns13wlbva2m64v97ybfqjx-gdk-pixbuf-2.38.1-dev/include/gdk-pixbuf-2.0 -I/nix/store/8z6xdhf6z2lb1y6h7380p3q8x2ya38d2-wayland-1.17.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O3  -MD -MQ 'oguri@exe/oguri.c.o' -MF 'oguri@exe/oguri.c.o.d' -o 'oguri@exe/oguri.c.o' -c ../oguri.c
../oguri.c: In function 'signal_handler':
../oguri.c:37:2: error: ignoring return value of 'write', declared with attribute warn_unused_result [-Werror=unused-result]
  write(signal_pipe[1], &number, sizeof(number));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../oguri.c: In function 'main':
../oguri.c:303:5: error: ignoring return value of 'write', declared with attribute warn_unused_result [-Werror=unused-result]
     write(client, &"okey dokey\n", 11);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

```

**Comment by vilhalmer** [comment]
Should be fixed in 03b66ae. I can't get it to yell at me about this locally even if I build with clang, what's your environment look like?

**Comment by colemickens** [comment]
The full GCC command is in there. Looks like:
 * gcc 7.4.0
 * `-Wall -Werror -Wextra -std=c11` maybe related to these ?

This didn't fix it though. Full log is here: https://gist.github.com/26c9eb60012ef2491e615273d9cd027b

**Comment by colemickens** [comment]
My build environment is in Nix: https://github.com/colemickens/nixpkgs-wayland/blob/master/pkgs/oguri/default.nix

**Comment by vilhalmer** [comment]
I have all the flags present, and werror=true in meson.build _should_ be leading to the same behavior, so I'm not sure what's preventing this warning. Apparently void cast has been broken in gcc for some time, so I guess I'll just do something stupid with the return value: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66425

**Comment by colemickens** [comment]
Weird, I'm not really sure of what else could be affecting why I was seeing the failure and you were not.

However, I can confirm that HEAD builds again nicely. Thank you very much for the fast turn around!

**Comment by vilhalmer** [comment]
The only thing I can think of is that I'm on gcc 8.3 and they've changed the criteria for the warnings. Thanks for packaging oguri!
